$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: chat_with_pdf
image: docker.io/modulesdkpreview/chat_with_pdf
inference_config:
  liveness_route:
    port: 8080
    path: /health
  readiness_route:
    port: 8080
    path: /health
  scoring_route:
    port: 8080
    path: /score
