name: tools_deploy_runtime

on:
  workflow_call:
    inputs:
      ToolsPackageVersion:
        type: string
        required: true
        description: 'Version of the promptflow-tools package to deploy'

jobs:
  deploy-runtime:
    runs-on: ubuntu-latest
    name: Deploy runtime with updated tools package

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9 environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Deploy runtime with updated tools package
        run: |
          python scripts/tool/deploy_endpoint.py --tool_pkg_version ${{ inputs.ToolsPackageVersion }} --ado_pat ${{ secrets.ADO_PAT }}
